### PR TITLE
fixed chosen selection of product selection on products detail page

### PR DESCRIPTION
**Pull request by proudcommerce**

### CODE REVIEW

**Comment by Sieg** [comment]
Hello @proudcommerce, could you please give more insight on this?

**Comment by proudcommerce** [comment]
>>> fixed chosen selection of product selection on products detail page
selected option is not saved --> please try in demo shop

**Comment by Sieg** [comment]
With this code, on selecting the variant, i see this:
image

**Comment by proudcommerce** [comment]
select list, not variants

**Comment by Sieg** [comment]
Thanks @proudcommerce, yes, the select of selectlists is working with this change. Regenerated the js assets and merged at d8f1e37fa67b59960e6f6b59ffee817af0e0aae3

**Pull request closed without merging**
