### PR TITLE
Form validation: missing error messages fixed

### PR DESCRIPTION
**Pull request by martin-hofer**
When validating a form (such as the user registration), Wave uses jqBootstrapValidation.js to display an error message below form fields that the user didn't fill out correctly. But this message is missing on the first such field. If only one field value is rejected by the validation, then the user sees no error message at all and is left confused.

The reason for this behavior is that

- the focus is automatically given to the topmost of the incorrectly filled fields, and
- these error messages automatically disappear as soon as the respective field receives the focus.

Thus, the error message is generated and then immediately deleted.

I added three lines to the main.js that unbinds the message-removing function from all events but onChange. Now, the error message stays displayed until the user changes the content of the field and the field loses the focus.

### CODE REVIEW

**Comment by keywan-ghadami-oxid** [comment]
I think I face the same issue so I added information about a alternative solution how I fixed this in https://github.com/OXID-eSales/wave-theme/pull/46 hoping that this is useful for reviewers or others facing the same issue.

**Comment by Sieg** [comment]
Hello @martin-hofer, how about unbinding only: "keyup", "focus", "blur" events?

**Comment by Sieg** [comment]
Hey @martin-hofer! Good job on this question! I have merged your suggestion with slight modification mentioned previously. Now it works great!

**Comment by Sieg** [comment]
I have additionally ported this fix to the flow theme. Thanks again!

**Pull request closed without merging**
