### PR TITLE
No more breadcrumbs in checkout

### PR DESCRIPTION
**Pull request by martin-hofer**
The breadcrumbs are not needed in the checkout, where we already have the checkout steps bar. Since the checkout should be as clean and un-distracting as possible, I propose we remove them.

### CODE REVIEW

**Comment by Sieg** [comment]
Hey @martin-hofer, could you please as addon to your suggestions/changes add a screenshot? Would help a lot to make decisions. Thanks in advance.

**Comment by martin-hofer** [comment]
Sure, no problem!

Before:
image

After:
image

**Comment by Sieg** [comment]
Hello @martin-hofer. Thanks for your interest in improving the product! For this pull request, we have decided to not take it, and leave those breadcrumbs in checkout as well for the consistency. Anyway, in case someone doesn't like them being there, it's quite easy to remove them by overwriting the layout_breadcrumb block in the module.

**Comment by kermie** [comment]
Am not pretty sure about it: wouldn't this be a nice little extension for those to don't want to have the bread crumb in checkout? Just a brain fart...

**Comment by keywan-ghadami-oxid** [comment]
most big customers don't want to have it in the checkout,
this is because designers and ux experts often suggest to remove it here and big customers do have such experts. one argument is that it looks better and the other is that they want to remove things that vould cause the customer to rethink about doing the order e.g. by going back with the breadcrumb.

I propose to remive by default (this makes big projects easier where every littel change involves a lot of people but and that maybe the bridge for all stakeholde to make it configurable in the theme settings.

**Comment by Sieg** [comment]
Hello guys! About "most big customers don't want to have it in the checkout,", I would say even more - they want their own design for the shop, and usually the whole checkout is changing :)

What we could do with This question - If we will make visibility configurable for the theme, and by default, breadcrumbs will be visible as they are now, then I don't see why it could not be merged.

What do you think?

**Pull request closed without merging**
