### PR TITLE
Several small fixes in forms

### PR DESCRIPTION
**Pull request by martin-hofer**
- Fixed for- and id-Attribute of oxuser__oxsal in user_billing.tpl (it had oxfname instead of oxsal)
- Added missing for- and id-Attributes to many lines in user_billing.tpl, user_shipping.tpl, newsletter.tpl, user_account.tpl and user_noaccount.tpl (this might seem a bit OCD, but it doesn't make sense to have them in some lines and not in others)
- Added missing help-block-Elements to salutations in user_billing.tpl and user_shipping.tpl (I don't know if they are technically needed, but not having them there screwed up the spacing between the form lines)
- fixed the bootstrap offset classes in newsletter.tpl (now offset-lg-2 instead of col-lg-offset-2)

### CODE REVIEW

**Comment by Sieg** [comment]
Hello @martin-hofer. Thanks for your improvements!

For next time, please, make separate pull requests and commits for different questions!

**Comment by martin-hofer** [comment]
Hi @Sieg, thanks for the feedback! Just so that I know how to do it correctly next time: How would you have split up this MR?
- one for the id and for attributes
- one for the help blocks
- and one for the offset classes?

**Comment by Sieg** [comment]
Yes, that would be great, as those parts are separate issues.

**Comment by martin-hofer** [comment]
@Sieg Thanks, I'll do it like this in the future!

**Pull request closed without merging**
