### PR TITLE
Update setup.sql

### PR DESCRIPTION
**Pull request by 8i11y**
Add mySQL "replace"-command to delete unnecessary hyphens from ID to fit it into char32

### CODE REVIEW

**Comment by Sieg** [comment]
Hey @8i11y, maybe md5 would be better solution then replace? :)

**Comment by 8i11y** [comment]
maybe g - I don't know... you mean something like this, then ?:
md5(uuid()), ?

**Comment by Sieg** [comment]
So right now - last 4 characters of that uuid() are just stripped away. If we will md5 it, we will have 32c hash from that 36c string, and it's much more readable then replace, and that's potentially less errors in the future for adding new values.

**Comment by 8i11y** [comment]
ok I will change it..
can I contact you in anyway (discord, slack etc.) I have a problem with the wave theme

**Comment by Sieg** [comment]
Hey @8i11y, you can contact me privately on myname at mysurname dot com :)

Regarding this PR, probably its not viable anymore, as you opened the new one #91 ? Closing this one then.

**Pull request closed without merging**
