### PR TITLE
Added a <span class="badge"> to the header's cart counter

### PR DESCRIPTION
**Pull request by martin-hofer**
In both headers (standard and sticky), the counter for the amount of articles in the cart is missing a span class="badge". This is why it looks different to the account button's counter (for articles on the wishlist etc.)

I added the missing span element.

### CODE REVIEW

**Comment by martin-hofer** [comment]
Before:
image

After:
image

**Comment by martin-hofer** [comment]
By the way, a similar fix was merged into the Flow theme a few months ago:

https://github.com/OXID-eSales/flow_theme/pull/138

**Comment by Sieg** [comment]
Hello @martin-hofer, i have squashed and reordered your commits a little. Could you please use pr44 branch for further improvements on this question please?

What we need to do first - make those badges working with bigger numbers, and make them bigger, as its too small, at least 10px font i would say.

**Comment by Sieg** [comment]
Hello @martin-hofer, are you planning to improve this? :)

**Comment by Sieg** [comment]
Hello @martin-hofer. I have improved the header part a little, to be working with bigger then one symbol numbers as well. Its now merged to b-1.x and up to master. Thank you for your improvement!

**Pull request closed without merging**
