### PR TITLE
Remove duplicate id of birthdate field

### PR DESCRIPTION
**Pull request by s-diez**

### CODE REVIEW

**Comment by flow-control** [comment]
Hey @s-diez,
nice catch :+1: 
I'll review
/Flo

**Comment by flow-control** [comment]
Hey @s-diez,

could you rebase this PR onto `b-1.x` branch and force push?
Targeting `v1.3.2` for this fix.

/Flo

**Comment by s-diez** [comment]
Hallo @flow-control,

Thanks for the fast response.

Should now be mergeable into b-1.x.

**Comment by flow-control** [comment]
Thanks very much :+1:

**Pull request merged**
