### PR TITLE
Manually revert changes made in commit 10cef8d6c64705f4b1f761773e4d34…

### PR DESCRIPTION
**Pull request by hansultra**
…14bac2c2da

to the file setup.sql and reimplemented the changes up to commit eb8b88f21fd77d433bbe531096739aa48a6e0632.

Reason:
Values inserted to "oxconfig.OXVARVALUE" are corrupted after commit
10cef8d6c64705f4b1f761773e4d3414bac2c2da.

https://github.com/OXID-eSales/wave-theme/commit/10cef8d6c64705f4b1f761773e4d3414bac2c2da#diff-ca29eebff2a52d087682a2063f89f3a1

### CODE REVIEW

**Comment by Sieg** [comment]
Hi @hansultra, could you please tell me more about your situation? What version of the shop you are using? Have you checked the compatibility branch information in the readme? I am quite sure I have tested this before merging and pushing, but maybe I have overlooked something.

**Comment by hansultra** [comment]
Dear sir,

by comparing the diff you can see that the decoded values (OXVARVALUE) committed
to "10cef8d6c64705f4b1f761773e4d3414bac2c2da" are truncated.

INSERT INTO `oxconfig` (`OXID`, `OXSHOPID`, `OXMODULE`, `OXVARNAME`, `OXVARTYPE`, `OXVARVALUE`, `OXTIMESTAMP`) VALUES

# Before

- (uuid(), 1, 'theme:wave', 'sFavicon16File', 'str', 0x79000644af5767e6228e5470901b92dbd5, NOW()),

... this inserts **"favicon_16x16.png"** (HEX-VALUE: 0x79000644af5767e6228e5470901b92dbd5)
  
# After

+ ('31f2b3b1-0aeb-11ea-9849-00163e13', 1, 'theme:wave',	'sFavicon16File', 'str', **'favi'**, '2019-11-19 17:40:26'),

... this inserts **"favi"**. The value for OXVARVALUE is currupted ?!

The same applies to other values inserted to `oxconfig` too.

I have installed OXID-Eshop with docker.
https://github.com/OXID-eSales/oxideshop_metapackage_ce/blob/b-6.2/composer.json

**Comment by Sieg** [comment]
@hansultra, thanks for pointing this out! Yes, looks like those config values were corrupted during the config decoding task. In the near future, those setup.sql files will be removed in master, as those were meant to be used in older shop versions where we had no configuration coming from theme.php file. Please ignore this for now, and use the default theme activation procedure which uses theme.php values for installation.

Let me know if we are missing something more and you really need those setup.sql files to stay, but with reasons ;)

Have a nice day!

**Comment by Sieg** [comment]
Hey @hansultra, wanted to inform you that we have removed the setup.sql in master already as I have been mentioning earlier (https://github.com/OXID-eSales/wave-theme/commit/4fbd6cbf61041fb2393531789b397a33576e53c4). Thanks again for pointing this out.

**Pull request closed without merging**
