### PR TITLE
Removed duplicate JS code from style.min.js

### PR DESCRIPTION
**Pull request by martin-hofer**
The current gruntfile compiles the following files (among others) into the main style.min.js:

- jqBootstrapValidation.js
- compare.js
- details.js
- review.js
- start.js

This is unnecessary, because these scripts are already included via oxscript on the pages that need them. I commented out the respective lines of the gruntfile and compiled a new version of style.min.js without these redundancies.

By the way: This bug was (and still is) also present in the flow theme:

- https://bugs.oxid-esales.com/view.php?id=6907

### CODE REVIEW

**Comment by Sieg** [comment]
Hi @martin-hofer, good you have noticed that. Maybe it will be better to cleanup those templates from separate inclusions of those scripts? Then we will have everything in one place. Will there be any problems if we will do like that?

**Comment by martin-hofer** [comment]
Hi Anton, I dont' think so - it' a matter of "fewer requests versus fewer bytes to download". If this code remains in separate files, it doesn't need to be downloaded for pages that don't use it. And having a few more requests usually doesn't slow a site down anymore, at least to my knowledge, since most people use HTTP2 anyway. That's why I did it this way.

But in this case, it doesn't make a huge difference: Excluding the redundant code from the script.min.js reduces the size of this file from 444 to 435 KB, so we're talking about a reduction of ~9 KB.

**Comment by Sieg** [comment]
Hello @martin-hofer. The problem with this solution is - IF one of the places where those scripts are used will not include that separate js file - we will have a problem. But the main scripts file is included everywhere, so you will not have any problems by removing those separate includes. So we cannot take this changes, as it is very risky.

**Comment by martin-hofer** [comment]
@Sieg It's your decision, of course - but I must admit that I don't fully get your reasoning.

If the inclusion of a necessary file on a page is forgotten, one would immediately see that in testing, since the page wouldn't work the way it should.

And if you check the performance of any site on something like Google PageSpeed Insights, the first thing it'll recommend is to "get rid of unnecessary code", as it slows down both loading and rendering time.

As I wrote above, I think in this case the difference is probably negligible and I'll be happy with either solution. But generally putting all the code in one big file, just so you don't need to keep an eye on where it is needed, is to my knowledge not the optimal strategy.

Anyway, thanks as always for the feedback! :-)

**Comment by Sieg** [comment]
Hey @martin-hofer! Yes, you are right with your statement that "one would immediately see that in testing"! But, sad to say - the current state of the tests are not allowing to see any problems with flow and wave themes :/ So, we cannot go for it Yet :)

**Pull request closed without merging**
